### ISSUE TITLE
Error `/usr/lib64/libnssutil3.so: version `NSSUTIL_3.82' not found (required by /opt/lib/libnss3.so)` during Lambda Execution

### ISSUE THREAD

**Issue by fucso** [fucso/sinatra-lambda-demo#3]
# Overview

Following error occurred on executing Lambda.
`sam local start-api` is working well.

```
{
    "errorMessage": "/usr/lib64/libnssutil3.so: version `NSSUTIL_3.82' not found (required by /opt/lib/libnss3.so) - /var/task/vendor/bundle/ruby/3.2.0/gems/pg-1.5.4/lib/pg_ext.so",
    "errorType": "Init<LoadError>",
    "stackTrace": [
        "<internal:/var/lang/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'",
        "<internal:/var/lang/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'",
        "/var/task/vendor/bundle/ruby/3.2.0/gems/pg-1.5.4/lib/pg.rb:49:in `block in <module:PG>'",
        "/var/task/vendor/bundle/ruby/3.2.0/gems/pg-1.5.4/lib/pg.rb:37:in `block in <module:PG>'",
        "/var/task/vendor/bundle/ruby/3.2.0/gems/pg-1.5.4/lib/pg.rb:42:in `<module:PG>'",
        "/var/task/vendor/bundle/ruby/3.2.0/gems/pg-1.5.4/lib/pg.rb:6:in `<top (required)>'",
        "<internal:/var/lang/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `require'",
        "<internal:/var/lang/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'",
        "<internal:/var/lang/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:40:in `require'",
        "/var/task/app/infrastructures/database.rb:1:in `<top (required)>'",
        "/var/task/app/usecases/plan/index.rb:1:in `require_relative'",
        "/var/task/app/usecases/plan/index.rb:1:in `<top (required)>'",
        "/var/task/app/controllers/plan.rb:2:in `require_relative'",
        "/var/task/app/controllers/plan.rb:2:in `<top (required)>'",
        "/var/task/app/routers/plan.rb:2:in `require_relative'",
        "/var/task/app/routers/plan.rb:2:in `<top (required)>'",
        "/var/task/app/server.rb:2:in `require_relative'",
        "/var/task/app/server.rb:2:in `<top (required)>'",
        "/var/task/app/config.ru:3:in `require_relative'",
        "/var/task/app/config.ru:3:in `block in <main>'",
        "/var/task/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:116:in `eval'",
        "/var/task/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:116:in `new_from_string'",
        "/var/task/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:105:in `load_file'",
        "/var/task/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:66:in `parse_file'",
        "/var/task/lambda.rb:22:in `<top (required)>'",
        "<internal:/var/lang/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'",
        "<internal:/var/lang/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'"
    ]
}
```

# Description

While developing #2 .
I created a script for deploy to Lambda. and fix it follow errors occurred on executing Lambda. 
ex) Lambda environment failing to locate certain binary packages,. So I adjusted Makefile for Lambda Layer.

However, the error cited above remains unresolved.

**Comment by fucso** [comment]
I tried configure `LD_LIBRARY_PATH ` environment variable of Lambda in several ways.

- `/opt/lib`

This path is lib directory provided by Lambda Layer.
In this case, Lambda was unable to load ruby runtime.

- `/opt/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib`

`/opt/lib` + default path pattern.
It's occurred same error of issue.

- `/opt/lib:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib`

Remove `/lib64` and `/usr/lib64` pattern.
`/opt/lib/libnss3.so` depends libnssutil3.so on `/usr/lib64`, so I thought if remove these path, `/opt/lib/libnss3.so` dependency become `/opt/lib`.
However, same error occurred.
